### ISSUE TITLE
mutilanguage support

### ISSUE THREAD

**Issue by bnomei** [omz13/kirby3-xmlsitemap#10]
will you add this eventually?

https://stackoverflow.com/questions/18423624/sitemap-for-domain-with-multilanguage-site#18423803

https://github.com/pedroborges/kirby-xml-sitemap
could do it maybe take a hint from there?

**Comment by omz13** [comment]
Eventually, yes (waiting multilanguage support to be a bit more stable before I implement).

**Comment by joernroeder** [comment]
need it too :)

**Comment by omz13** [comment]
I have it working now and have one last fix or three to do.

**Comment by omz13** [comment]
Getting a 500 on $page->urlForLanguage  - see k-next/kirby#1169 - can workaround, but its ugly.

**Comment by omz13** [comment]
Some metadata not correct for translated content... because `$p->content( $languageCode)` not working for `$languageCode` - see k-next/kirby#1170

**Comment by omz13** [comment]
Missing translation files? k-next/kirby#1173
