### ISSUE TITLE
[Feature Request] Optionally Include Images of Excluded Pages

### ISSUE THREAD

**Issue by luxlogica** [omz13/kirby3-xmlsitemap#11]
On one-pagers, often we don't want the page's sub-pages to show in the sitemap - as these are only 'sections' on the main page - but we DO want to incude the *images* of these sub-pages.

Example: "Home Page" is a one-pager, with sub-pages for 'About Us' (with images for the team), 'Case Studies' (with images), and a 'Portfolio' section (with lots of images). Although we don't want to list those as 'pages' in the sitemap, we do want their images to show up in the map as 'being under' the Home Page.

**Comment by omz13** [comment]
You can do this already: use `excludeChildrenWhenTemplateIs` - this excludes the children's _content_ from being included in the sitemap, but it does include their _images_ under their "parent".

The name is a bit confusing... TODO: clarify in the docs.
