### ISSUE TITLE
"Unbound XML namespace prefix" error in Google Search Console

### ISSUE THREAD

**Issue by MathiasGmeiner** [omz13/kirby3-xmlsitemap#12]
For this sitemap: https://www.restaurantkatrina.at/sitemap.xml I get an error in the Google Search Console.

It says:
**Unbound XML namespace prefix**
```
The XML Sitemap cannot be parsed because it contains one or more unbound namespace prefixes. For example, this error is generated when <xhtml:link> is found in a Sitemap without prior xmlns:xhtml="http://www.w3.org/1999/xhtml".
Line: 6

**Comment by omz13** [comment]
Ah. Its to do with mutilanguage. Will look.
@MathiasGmeiner  just to check, you run this site in multilanguage mode but only have one language? And your locale is de_DE and not de_AT?

**Comment by MathiasGmeiner** [comment]
Yes, currently it is just one language. But eventually they need a second language, that's the reason for my decision to create this multilingual-setup. My locale is de_DE, that's correct!
