### ISSUE TITLE
cache name with major version

### ISSUE THREAD

**Issue by bnomei** [omz13/kirby3-xmlsitemap#4]
when implementing a cache consider giving the file a name including the major version of your plugin. this will allow you to devalidate the cache on major version changes automatically.

```php
$cachename = 'sitemap-' . kirby()->plugin('omz13/kirby3-xmlsitemap')->version()[0];
kirby->cache('omz13.kirby3-xmlsitemap')->set($cachename, $sitemapString);
```

**Comment by omz13** [comment]
In 0.4, I have implemented caching using the plugin cache facility (see the _Cache Concepts_ document on notion)... the namespace is set automatically by kirby (so perhaps kirby should include the plugins version number)... but, just in case, I prefix a few parameters to the name when saving the page to the cache... in the next version I will add a bit more - to effectively cache bust vis-à-vis the options...

https://github.com/omz13/kirby3-xmlsitemap/blob/757b4130ce1ef5547f79c2ecf2a1a187b0618df1/src/xmlsitemap.php#L111-L116
