### ISSUE TITLE
dev-master as 1.0.0 fails

### ISSUE THREAD

**Issue by bnomei** [omz13/kirby3-xmlsitemap#9]
```
The requested package omz13/kirby3-xmlsitemap (locked at 0.4.3, required as dev-master as 1.0.0) is satisfiable by omz13/kirby3-xmlsitemap[0.4.3] but these conflict with your requirements or minimum-stability.
```

maye you need to increase version to 1.x instead of being below?

**Comment by omz13** [comment]
I changed the build process for 0.4.3 and it did not work as I expected... I will push out a new build that will - I hope - be better.

(My fault for not trying this out on a develop branch)
